"""add menu combo constituents

Revision ID: 697ee3a84f1e
Revises: 1f0eff7ba2b0
Create Date: 2026-03-26 15:17:35.283305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697ee3a84f1e'
down_revision: Union[str, Sequence[str], None] = '1f0eff7ba2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_constituents',
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('child_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_constituents_child_item_id_menu_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_constituents_parent_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_item_id', 'child_item_id', name=op.f('pk_menu_item_constituents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_constituents')
    # ### end Alembic commands ###
