"""add kitchen tables

Revision ID: 6fff701162a9
Revises: 67feb20cf681
Create Date: 2026-03-15 00:05:05.708595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fff701162a9'
down_revision: Union[str, Sequence[str], None] = '67feb20cf681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('stage_updated_at', sa.String(), server_default="(datetime('now'))", nullable=False),
    sa.Column('stage_updated_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default="(datetime('now'))", nullable=False),
    sa.CheckConstraint("stage IN ('queued','prepping','baking','cooling','decorating','packed','assigned')", name='ck_kitchen_batches_stage'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['stage_updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_batch_order_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.String(), server_default="(datetime('now'))", nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['kitchen_batches.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_stage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.String(), server_default="(datetime('now'))", nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['kitchen_batches.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitchen_stage_log')
    op.drop_table('kitchen_batch_order_assignments')
    op.drop_table('kitchen_batches')
    # ### end Alembic commands ###
