"""add_status_to_order_items

Revision ID: 7b28bc3c16b5
Revises: 841fc4f97067
Create Date: 2026-03-18 19:58:18.146138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b28bc3c16b5'
down_revision: Union[str, Sequence[str], None] = '841fc4f97067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='pending', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
