"""Add menu items table

Revision ID: a4e15f8b495d
Revises: ae78a9879db2
Create Date: 2026-03-13 20:25:56.771473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e15f8b495d'
down_revision: Union[str, Sequence[str], None] = 'ae78a9879db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('size_unit', sa.String(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    # ### end Alembic commands ###
